# Generated by Django 6.0.6 on 2026-07-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_description_alter_task_priority_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["deadline", "priority", "name"]},
        ),
    ]
